GET http://localhost:8000/v1/launches

###

GET http://localhost:8000/v1/launches?limit=5&page=1

###

POST http://localhost:8000/v1/launches
Content-Type: application/json

{
    "mission": "ZMT155",
    "rocket": "ZTM Experimental IS1",
    "target": "Kepler-186 f",
    "launchDate": "January 17, 2030"
}

###
DELETE http://localhost:8000/v1/launches/115